# Generated by Django 4.0.6 on 2022-07-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubricapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completion_of_tasks',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='interest',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='team_work',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='understanding',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='discovery',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
